import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";
/**
 * 자체 SVG 아이콘 → React 컴포넌트 변환.
 * src/custom/svg/*.svg → src/custom/generated.ts
 *
 * SVG 요구사항:
 *  - viewBox="0 0 24 24"
 *  - stroke-width="1.5"
 *  - stroke="currentColor", fill="none" (또는 currentColor)
 *  - 파일명 = PascalCase 컴포넌트명 (예: agent-status.svg → AgentStatus)
 */
import { transform } from "@svgr/core";

const SVG_DIR = "src/custom/svg";
const OUT_FILE = "src/custom/generated.ts";

const toPascalCase = (str) =>
  str
    .replace(/[-_]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
    .replace(/^./, (c) => c.toUpperCase());

async function main() {
  let files;
  try {
    files = (await readdir(SVG_DIR)).filter((f) => f.endsWith(".svg"));
  } catch {
    await mkdir(SVG_DIR, { recursive: true });
    files = [];
  }

  if (files.length === 0) {
    await writeFile(OUT_FILE, "// no custom icons yet\nexport {};\n");
    console.log("ℹ️  No custom SVGs found. Wrote empty generated.ts.");
    return;
  }

  const exports = [];
  for (const file of files) {
    const name = toPascalCase(basename(file, extname(file)));
    const svg = await readFile(join(SVG_DIR, file), "utf8");
    const jsx = await transform(
      svg,
      {
        plugins: ["@svgr/plugin-jsx"],
        typescript: true,
        jsxRuntime: "automatic",
        icon: true,
        replaceAttrValues: { "#000": "currentColor", "#000000": "currentColor" },
      },
      { componentName: name },
    );
    exports.push(jsx.replace(/^import.+$/gm, "").trim());
    exports.push(`export { ${name} };\n`);
  }

  await writeFile(
    OUT_FILE,
    `// Generated by build-custom.mjs. Do not edit.\nimport type { SVGProps } from "react";\n\n${exports.join("\n")}\n`,
  );
  console.log(`✅ Generated ${files.length} icons → ${OUT_FILE}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
